name: github_followers
description: GitHub Followers.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  webview_flutter: ^2.0.13

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: lib/resources/fonts/Roboto-Bold.ttf
          weight: 800
        - asset: lib/resources/fonts/Roboto-BoldItalic.ttf
          weight: 800
        - asset: lib/resources/fonts/Roboto-Black.ttf
          weight: 700
        - asset: lib/resources/fonts/Roboto-BlackItalic.ttf
          weight: 700
        - asset: lib/resources/fonts/Roboto-Italic.ttf
          weight: 600
        - asset: lib/resources/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: lib/resources/fonts/Roboto-MediumItalic.ttf
          weight: 500
        - asset: lib/resources/fonts/Roboto-Light.ttf
          weight: 300
        - asset: lib/resources/fonts/Roboto-LightItalic.ttf
          weight: 300
        - asset: lib/resources/fonts/Roboto-Regular.ttf
          weight: 400

